### ISSUE TITLE
Wrong installation path on blender-2.79-windows64.zip

### ISSUE THREAD

**Issue by 1138-4EB** [Kirpal/Keyboard-Layout-Editor-for-Blender#23]
I am using [blender-2.79-windows64.zip](https://www.blender.org/download/Blender2.79/blender-2.79-windows64.zip/), which is a portable version. When the addon is installed, as explained in the README, it is copied to `C:\Users\<USER>\AppData...`. However, it should be copied to a path relative to where the binary is located: `...\blender-2.79-windows64\2.79\scripts\addons`. These are the steps I followed to have it installed:

1. Create a new subdir in `...\blender-2.79-windows64\2.79\scripts\addons` named `io_kle`.
2. Extract the content of the release zip file (`v2.4.zip`) to the created subdir.
3. Follow steps 6-9 of the README.
4. Remove `C:\Users\<USER>\AppData\Roaming\Blender Foundation`.

---

I get the following error when [this](http://www.keyboard-layout-editor.com/##@@_c=#d31929&a:7&w:1.25&n:true;&=%0A%0A%0A%0Aesc&_c=#2d3238&t=#ffffff&a:0;&=%0A%0A%0A%7C%0A1%0A!&=%0A%0A%0A/@%0A2%0A%22&=%0A%0A%0A#%0A3%0A%C2%B7&=%0A%0A%0A~%0A4%0A$&_c=#525554&n:true;&=%0A%0A%0A%E2%82%AC%0A5%0A%25&_c=#2d3238;&=%0A%0A%0A%C2%AC%0A6%0A/&&_a:3;&=%0A%0A%0A%0A7%0A//&=%0A%0A%0A%0A8%0A(&=%0A%0A%0A%0A9%0A)&_c=#525554&n:true;&=%0A%0A%0A%0A0%0A/=&_c=#2d3238;&=%0A%0A%0A%0A'%0A?&=%0A%0A%0A%0A%C2%A1%0A%C2%BF&_c=#0078a3&a:7&w:1.25;&=%0A%0A%0A%0AbackSpace&_x:0.25&c=#2d3238&a:5;&=%0AprtSc%0A%0A%0A//&=%0AscrLk%0A%0A%0A*&=%0Apause%0A%0A%0A-;&@_c=#0078a3&t=#000000&a:7&w:1.25;&=%0A%0A%0A%0Atab&_c=#d9dae0;&=%0A%0A%0A%0AQ&=%0A%0A%0A%0AW&=%0A%0A%0A%0AE&=%0A%0A%0A%0AR&=%0A%0A%0A%0AT&=%0A%0A%0A%0AY&=%0A%0A%0A%0AU&=%0A%0A%0A%0AI&=%0A%0A%0A%0AO&=%0A%0A%0A%0AP&_c=#2d3238&t=#ffffff&a:0;&=%0A%0A%0A%5B%0A%60%0A%5E&=%0A%0A%0A%5D%0A+%0A*&_c=#95bfe8&a:7&w:1.25&h:2;&=%0A%0A%0A%0Aenter&_x:0.25&c=#d9dae0&t=#000000&a:5;&=%0Ains%0A%0A%0A7&=%0Ahome%0A%0A%0A8&=%0ApgUp%0A%0A%0A9;&@_c=#00a477&t=#ffffff&a:7&w:1.25;&=%0A%0A%0A%0AcapsLk&_c=#d9dae0&t=#000000;&=%0A%0A%0A%0AA&=%0A%0A%0A%0AS&=%0A%0A%0A%0AD&_n:true;&=%0A%0A%0A%0AF&=%0A%0A%0A%0AG&=%0A%0A%0A%0AH&_n:true;&=%0A%0A%0A%0AJ&=%0A%0A%0A%0AK&=%0A%0A%0A%0AL&=%0A%0A%0A%0A%C3%91&_c=#2d3238&t=#ffffff&a:0;&=%0A%0A%0A%7B%0A%C2%B4%0A%C2%A8&=%0A%0A%0A%7D%0A%C3%A7%0A%C3%87&_x:1.5&c=#d9dae0&t=#000000&a:5;&=%0Adel%0A%0A%0A4&=%0Aend%0A%0A%0A5&=%0APgDn%0A%0A%0A6;&@_c=#0078a3&a:7&w:1.25;&=%0A%0A%0A%0Ashift&_c=#2d3238&t=#ffffff&a:3;&=%0A%0A%0A%0A%3C%0A%3E&_c=#d9dae0&t=#000000&a:7;&=%0A%0A%0A%0AZ&=%0A%0A%0A%0AX&=%0A%0A%0A%0AC&=%0A%0A%0A%0AV&=%0A%0A%0A%0AB&=%0A%0A%0A%0AN&=%0A%0A%0A%0AM&_c=#2d3238&t=#ffffff&a:3;&=%0A%0A%0A%0A,%0A/;&=%0A%0A%0A%0A.%0A/:&=%0A%0A%0A%0A-%0A/_&_c=#525554&a:0;&=%0A%0A%0A%5C%0A%C2%BA%0A%C2%AA&_c=#0078a3&t=#000000&a:7&w:1.25;&=%0A%0A%0A%0Ashift&_x:0.25&c=#d9dae0;&=%0A%0A%0A%0A1&_c=#95bfe8&t=#ffffff&a:5;&=%0A%E2%86%91%0A%0A%0A2&_c=#d9dae0&t=#000000&a:7;&=%0A%0A%0A%0A3;&@_c=#0078a3&w:1.25;&=%0A%0A%0A%0Actrl&_c=#00a477&t=#ffffff;&=%0A%0A%0A%0Asuper&_c=#2d3238;&=&_c=#0078a3&t=#000000&w:1.25;&=%0A%0A%0A%0Aalt&_c=#95bfe8&w:4.5;&=&_c=#0078a3&w:1.25;&=%0A%0A%0A%0AaltGr&_c=#00a477&n:true;&=%0A%0A%0A%0Afn&_c=#2d3238&t=#ffffff;&=%0A%0A%0A%0Amenu&_c=#00a477;&=%0A%0A%0A%0AnumLk&_c=#0078a3&t=#000000&w:1.25;&=%0A%0A%0A%0Actrl&_x:0.25&c=#95bfe8&t=#ffffff&a:5;&=%0A%E2%86%90%0A%0A%0A0&=%0A%E2%86%93%0A%0A%0A00&_a:4;&=.%0A%0A%0A%0A%0A%0A%0A%0A%0A%0A%E2%86%92) layout is loaded:

![kirpal_kle_error](https://user-images.githubusercontent.com/6628437/36788008-979495c4-1c8c-11e8-97ad-513f69150c41.png)

But the preset layouts work as expected. Might it be relatd to (CSS) styles? Am I missing some other dependency?

**Comment by Kirpal** [comment]
I believe the installation bug is related to blender? The addon itself doesn't install anything, it just uses blender's own mechanism.

As for the error message, it's due to the front legends. They're not currently supported, although it's on the To Do
