### ISSUE TITLE
Does not work in Blender 2.8

### ISSUE THREAD

**Issue by lbibass** [Kirpal/Keyboard-Layout-Editor-for-Blender#25]
Not sure what is going wrong here, given that I am not an expert on Blender, but it's pretty weird. It works on 2.7.9, but not 2.8.

Here's the error message. 
![screen shot 2018-03-01 at 5 35 42 pm](https://user-images.githubusercontent.com/27320050/36873972-324ed200-1d78-11e8-8522-4f38a325cab9.png)

**Comment by Kirpal** [comment]
Looks like there were some [python API changes](https://wiki.blender.org/index.php/Dev:2.8/Source/LayersCollections/API-Changes) in 2.8. I'm going to try to figure out how to support both versions. Blender script documentation is pretty poor.

**Comment by lbibass** [comment]
also @Kirpal unicode characters still do not work, any chance they could be added in?

**Comment by Kirpal** [comment]
What layout are you using? I think it may be your font.

**Comment by Kirpal** [comment]
@lbibass

**Comment by lbibass** [comment]
@Kirpal ack, my bad. I'm just using the stock KLE font, which as far as I can tell, I cannot change. 

Any fixes?
