### ISSUE TITLE
Can't activate, doesn't show up in Addon List

### ISSUE THREAD

**Issue by Memnarch1113** [Kirpal/Keyboard-Layout-Editor-for-Blender#26]
This looks really sweet! Unfortunately, I tried to install it into Blender 2.79 and it doesn't show up in the user preferences list to activate. I've tried importing both the whole zip file and just the "keyboard_importer.py" file. If I uncheck "overwrite" while importing it shows that something is installed already. I'm running on Windows, with the 64bit version of blender (installed, not from a zip). Any help would be appreciated.

**Comment by Memnarch1113** [comment]
I manually added a folder in the blender install directory: ``C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\`` called kle_import. I dragged the files from the release zip (2.4) into it and refreshed the addons page in Blender, and it showed up just fine. No idea what that was about!

**Comment by Kirpal** [comment]
Weird! Let me know if you have any other problems
