### ISSUE TITLE
Vertically stacked legends possible or not? 

### ISSUE THREAD

**Issue by the1THRILLHOUSE** [Kirpal/Keyboard-Layout-Editor-for-Blender#27]
Hey guys just wanted to point this out, not sure if its an available feature or if this is a glitch

 ![stacked enter/return on 1x2u key](https://i.imgur.com/6vWro4N.png)

It would appear that stacking the numpad return key so that the letters are vertical makes the text box outline (the triangles above and below the text) visible in all renders. 

I've tried adjusting the legend size to maybe eliminate the problem, but it would appear that it doesn't matter. 

 ![legend size comparison](https://i.imgur.com/4pZMN2E.png)

Is this a possible feature that I'm simply having problems with or is this a feature not yet added to this plugin?

Thanks!

**Comment by Kirpal** [comment]
Can you share the layout you're using?

**Comment by the1THRILLHOUSE** [comment]
f me...i deleted the entire layout except the numpad return trying to isolate it...

totally different color scheme but here's the template I used to prep my color scheme. 

http://www.keyboard-layout-editor.com/#/gists/3484177a8bb20a8de7e77138413be4ee

**Comment by Kirpal** [comment]
Looks like that layout's working for me:
![screenshot from 2018-03-03 19-09-59](https://user-images.githubusercontent.com/18384371/36940697-bf8f42c2-1f16-11e8-8060-cf700f59dcd5.png)
Does this new one work for you?

**Comment by the1THRILLHOUSE** [comment]
hmmm wierdly enough it does work, i lose the triangles, but one letter looks like its a completely different size than the rest...

wonder if its something internal or specific to my gpu/computer or something

![large N](https://i.imgur.com/29QzkML.png)

**Comment by Kirpal** [comment]
It looks like that's a different font than mine... Weird question, but is your computer connected to the internet? Maybe it's not downloading the font?

**Comment by the1THRILLHOUSE** [comment]
yah it is....odd....i'll tinker around and get back to this, try and figure out what the deal is.

**Comment by Kirpal** [comment]
Let me know what you find, or if I can help at all.

**Comment by Kirpal** [comment]
Did you figure this out?
