### ISSUE TITLE
Can't install into Blender 2.79

### ISSUE THREAD

**Issue by DannyMcGillick** [Kirpal/Keyboard-Layout-Editor-for-Blender#29]
I may be messing it up somehow, but I've downloaded v2.6 and v2.5 zips and tried to install add-on from file but it just drops back to the add-on list with no addition of the import-export plugin.

Using Blender 2.79 on Windows 10.

**Comment by Kirpal** [comment]
Try unzipping it directly to `C:\Users\%username%\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons`, then restarting blender, opening user preferences, and enabling the add-on

**Comment by DannyMcGillick** [comment]
Thanks, will do!  Making goofy-assed keyboard ideas a sort of reality :)

**Comment by kpeatt** [comment]
This isn't working for me on OSX Blender 2.79 either. I see the file in the addons folder but it doesn't appear in my addons list :(

**Comment by kpeatt** [comment]
Managed to fix my issue by manually making a folder for it inside the `addons` folder.

**Comment by Kirpal** [comment]
Sorry, that's what I meant. Should've been more clear.
