### ISSUE TITLE
Front Legends Causes Error on Import

### ISSUE THREAD

**Issue by Loffeno** [Kirpal/Keyboard-Layout-Editor-for-Blender#30]
If you try to import a .json that has keys with front legends, it fails to import. I'll attach a file that cause it, though any file with front legends should replicate the issue.
[error.zip](https://github.com/Kirpal/Keyboard-Layout-Editor-for-Blender/files/1823176/error.zip)

**Comment by Kirpal** [comment]
Front legends aren't supported currently, and I haven't figured out a way to support them yet. I will however fix the crashing from front legends and just not have them put into the model.
