### ISSUE TITLE
Addon not installing

### ISSUE THREAD

**Issue by deadencryption** [Kirpal/Keyboard-Layout-Editor-for-Blender#31]
I perform all the steps listed. But after I click Install on the top right there isn't any import: KLE option to click a checkbox at all.

**Comment by Kirpal** [comment]
What's your OS? Blender version?

**Comment by deadencryption** [comment]
Win 10-64bit. I believe it's blender 2.79. I did the folder extract workaround and it added it. But using the add-on from file.method does not work.




Dave Cruz


CEO - President




P: 210-816-3756


C: 210-857-0622


P.O. Box 88


Helotes, TX 78023 USA




https://www.fiosta.com







From: Kirpal Demian


Sent: Sunday, April 1, 8:36 AM


Subject: Re: [Kirpal/Keyboard-Layout-Editor-for-Blender] Addon not installing (#31)


To: Kirpal/Keyboard-Layout-Editor-for-Blender


Cc: deadencryption, Author






What's your OS? Blender version?

**Comment by Kirpal** [comment]
Should be fixed now with the latest release
