### ISSUE TITLE
Help -- Addon Install

### ISSUE THREAD

**Issue by write-click** [Kirpal/Keyboard-Layout-Editor-for-Blender#35]
I've been trying to get this install to work for a couple hours now -- and cannot get this addon to install properly on a mac osx 10.13.4

Installing through the zip puts the addon in a different location under user rather than with the rest of the addons -- it seems to be installed but doesn't show up in the list. 

Closest I've gotten it to work is to first install through the zip and then move the folder to the other  location -- this at least forced the addon to show up in the list and let me enable it.

But these were the result upon import...

Any advice?
<img width="1116" alt="screenshot 2018-04-13 01 04 26" src="https://user-images.githubusercontent.com/38285588/38710131-ac19bc62-3eb6-11e8-946c-01c889ec1a74.png">

**Comment by Kirpal** [comment]
Please try the latest release and let me know if there are still these issues
