### ISSUE TITLE
Atreus layout does not import properly

### ISSUE THREAD

**Issue by d4mation** [Kirpal/Keyboard-Layout-Editor-for-Blender#37]
I tried both the Atreus preset in KLE and the Atreus62 KLE file made by jowe over on geekhack [here](http://www.keyboard-layout-editor.com/#/gists/ba3723e5507de945f8a2954fe8877d16)

I'm also using the Blender Scene from the README.

The Atreus preset in KLE turns out better than the Atreus62, but neither appear to import correctly. Perhaps it is related to #36 somehow?

The Atreus preset seems mostly fine on the left-hand side, but the right-hand explodes out. A lot of the left-hand side also goes behind the backdrop.
![image](https://user-images.githubusercontent.com/7770631/39062747-81a2dd70-4496-11e8-84c8-c5ba3b697c45.png)

Here's the User Perspective preview pane rotated upward to show behind the backdrop.
![image](https://user-images.githubusercontent.com/7770631/39063019-8c08dc78-4497-11e8-8fc8-d9e91e6e51e3.png)

The Atreus62 one however appears to be straight up missing most keys. I'm not sure if that's a configuration issue in KLE or not truthfully. 

![image](https://user-images.githubusercontent.com/7770631/39062956-544a834a-4497-11e8-8fb7-737ed1e4cd02.png)

---

Thanks for this tool, by the way! Despite not being able to render an Atreus62 as I wanted, I was able to successfully render out a regular 60% board to get an idea of the colors I'm looking at for the keycaps. Being able to see a "real world" example of the colors side-by-side was very helpful 😃

**Comment by d4mation** [comment]
Also, if it helps, I'm using this addon at ff731649234ff736df6eb6dd322b25e6d8a982e4 as I couldn't get the ZIP from the releases tab to install properly otherwise. It seems that it is extracting directly into the Addons Directory rather than to its own Directory within the Addons Directory when I use the latest Release ZIP:

![image](https://user-images.githubusercontent.com/7770631/39063781-2459a14a-449a-11e8-9d8b-50a852c5188e.png)

**Comment by Kirpal** [comment]
The install bug should be fixed, working on the rotation now.

**Comment by d4mation** [comment]
That fixed it, thanks!
