### ISSUE TITLE
Failed to install the addon

### ISSUE THREAD

**Issue by hhkbp2** [Kirpal/Keyboard-Layout-Editor-for-Blender#39]
Hi,

I follow the instructions and try to install the addon to blender, but run into a problem:

> 6. Select the zip archive that you downloaded and click Install from File… at the top right
> 7. Check the checkbox next to Import-Export: Import: KLE Raw JSON format (.json)

After 6 is done, there is no such item(and no such checkbox) in Import-Export. Does it mean the addon is not installed properly? Or any other thing is wrong? I used Blender v2.79b and addon v2.9.

**Comment by Kirpal** [comment]
What OS are you using?

**Comment by hhkbp2** [comment]
It's Mac OS X.

I think I figure it out: the release packages of v2.9 ~ v2.7 are invalid. Unzip them only get empty directories. While it gets a bunch of files by unzipping the v2.6 zip file. And it works ok as the install and usage instructions say after I copy the v2.6 unzipped files into the blender script directory. The whole blender would crash sometime using v2.6 while doing import json file, but it seems workable.

**Comment by Kirpal** [comment]
Was a problem with the script I was using to publish the release, should be fixed in 2.10
