### ISSUE TITLE
Broken sculpt issues (SA R1,2)

### ISSUE THREAD

**Issue by plexabyte** [Kirpal/Keyboard-Layout-Editor-for-Blender#40]
I've found some issues with rendering row 1 and 2 in SA profile. There's lines through the profile, as you can see here: 
![sa oblivion](https://i.imgur.com/fcA4fAM.png)

Not sure what the issue is, and I'm pretty new to blender.

**Comment by Kirpal** [comment]
Can you post a link to the layout?

**Comment by plexabyte** [comment]
Thanks for the reply. Pretty sure it was this one.

http://www.keyboard-layout-editor.com/#/gists/103892d9c434c0d7b7016aea0858edd7
