### ISSUE TITLE
Font issues for DSA keycaps with multiple size legends.

### ISSUE THREAD

**Issue by JwordFish** [Kirpal/Keyboard-Layout-Editor-for-Blender#42]
Hey this tool is awesome. I noticed a couple issues importing a DSA layout: default font is not importing (though the font it's using looks pretty good), keycaps with multiple font sizes are importing as the same size; bottom legends are getting cut off below the baseline.

Thanks!

<img width="271" alt="screen shot 2018-07-14 at 11 36 55 am" src="https://user-images.githubusercontent.com/38897243/42726131-a1f675dc-875d-11e8-811a-65a496c5c946.png">
<img width="273" alt="screen shot 2018-07-14 at 11 39 16 am" src="https://user-images.githubusercontent.com/38897243/42726132-a208310a-875d-11e8-8750-51c7311cf5d2.png">

**Comment by Kirpal** [comment]
Please post the layout

**Comment by JwordFish** [comment]
Attached, thanks! [keyboard-layout-9.json.zip](https://github.com/Kirpal/Keyboard-Layout-Editor-for-Blender/files/2195853/keyboard-layout-9.json.zip)

**Comment by Kirpal** [comment]
Reopened for font clipping issue

**Comment by Kirpal** [comment]
The different default font is to be more realistic, it looks more similar to PMK's font
