### ISSUE TITLE
Arrow icons not rendering

### ISSUE THREAD

**Issue by mikethetiger** [Kirpal/Keyboard-Layout-Editor-for-Blender#45]
Arrow icons don't seem to render. They show up as jumbled words or a box with an "x" in it.

**Comment by Tedfs3** [comment]
I'm no expert but I think this is due to the fonts used by the plugin not supporting symbols ? Ran into the same issue and just ended up changing it to text.

**Comment by mikethetiger** [comment]
I got you. I just wanted to have a more accurate render of my upcoming keyset. Love the plugin!! Keep up thew good work.

**Comment by Kirpal** [comment]
Which font and symbols are you trying to use?

**Comment by mikethetiger** [comment]
I tried the various arrows available on KLE. I even copied over the ones used on the kbrenders.com site and none work. Supposedly, kbrenders.com also uses blender.

**Comment by Morid1n** [comment]
Having a similar issue for _all_ non-standard characters, including HTML arrows, Font Awesome, etc.

Any ideas how to solve this issue?

**Comment by BlitzKraft** [comment]
Is it possible that there is a unicode support issue?

**Comment by SHIFT1672** [comment]
I'm getting the same problem... Anyway to fix this?

**Comment by Kirpal** [comment]
Can you post a link to your layout, please?

**Comment by shinjikun1011** [comment]
JSON file worked great on KBrenders but when imported using the addon into blendor no arrows or any special characters show.

**Comment by Kirpal** [comment]
HTML arrows/glyphs are now supported (on master, not released yet). Working on adding KLE glyphs and FA

**Comment by shinjikun1011** [comment]
If Hiragana could be supported, that would be amazing. Thank you for this wonderful add-on.

**Comment by Kirpal** [comment]
@shinjikun1011 Could you please post an example layout that isn't working?

**Comment by shinjikun1011** [comment]
http://www.keyboard-layout-editor.com/#/gists/b571f4c0e23eed6f52e8c88e9f1cdea2

The arrow keys are the standard ones in KLE and they dont render properly in 2.79. Thank you so much for any help. 
[jis-keyboard-only-full.zip](https://github.com/Kirpal/Keyboard-Layout-Editor-for-Blender/files/3809040/jis-keyboard-only-full.zip)
