### ISSUE TITLE
Add Support for Blender 2.8

### ISSUE THREAD

**Issue by dmcgits** [Kirpal/Keyboard-Layout-Editor-for-Blender#46]
Hiya guys, I saw a similar issue and it was closed. I figured it was in there as a bug but I'm wondering if we could have it here as a feature request? If not, thanks for reading!

I'll try to figure it out by googling around but if anyone could point me toward the specific broken bits and any _blender 2.8 API docs_ I can start looking into it. I'm new to _Python_ but have coded _as3/c#/c++_ at work and use _Maya/ZB/Painter/Unity_ etc.

**Comment by Kirpal** [comment]
Yeah now that 2.8 is out this is definitely something it needs. I'll keep trying to find good documentation of the API changes, if I remember correctly there were some pretty fundamental things that would need refactoring in the add-on to be compatible.

**Comment by dmcgits** [comment]
Thanks for getting back! I got a start on it tonight but also spent hours
getting the touchpad to work when a macbook running linux wakes up :D

**Comment by gracjanzlotucha** [comment]
Any updates on that?

**Comment by syrah94** [comment]
is there any update on bringing this add-on up to date?

**Comment by FakeDazon** [comment]
any updates? no rush.

**Comment by Kirpal** [comment]
Finished this, please open further issues if you find any bugs that made it through
