### ISSUE TITLE
Issue installing add-on, says I need to upgrade to 2.8x, but I have 2.8.

### ISSUE THREAD

**Issue by ionsnail** [Kirpal/Keyboard-Layout-Editor-for-Blender#48]
I installed the add-on, and it keeps telling me to upgrade to blender 2.8x, yet I have the most recent version of blener 2.8. Is there anything I can do?

Thanks so much.

![freekanye2020](https://user-images.githubusercontent.com/46383443/57904250-8b78e080-7837-11e9-95d5-36de15fb269d.png)

**Comment by Kirpal** [comment]
This is due to the add-on itself needing too be updated, I'll do that over the next few days. Closing, please see #46

**Comment by ionsnail** [comment]
Fantastic, great work!
