### ISSUE TITLE
Help? :-)

### ISSUE THREAD

**Issue by iandoug** [Kirpal/Keyboard-Layout-Editor-for-Blender#5]
Hi

Followed instructions, am able to import KLE json file, but all I get on screen is a row of different sized buttons and a big cube. Tried two different json files.

When I was installing your addon Blender complained about some "cycles" (IIRC) file being missing.

Am a total noob with Blender, installed it today just to use your tool.

Installed versions:  2.79

Any ideas?

Thanks, Ian

**Comment by Kirpal** [comment]
Where did you download blender from? Try reinstalling both blender and the addon, and if it errors out again post the message here.

**Comment by iandoug** [comment]
I'm on Gentoo, we compile from source. Maybe one of the "-" flags below may be incorrect:

 eix blender
[I] media-gfx/blender
     Available versions:  2.72b-r4 (~)2.79 {+boost +bullet collada colorio cuda cycles +dds debug doc +elbeem ffmpeg fftw +game-engine headless jack jemalloc jpeg2k libav llvm man ndof nls openal opencl +openexr openimageio openmp +opennl opensubdiv openvdb osl player redcode sdl sndfile test tiff valgrind CPU_FLAGS_X86="sse sse2" PYTHON_SINGLE_TARGET="python3_5 python3_6" PYTHON_TARGETS="python3_4 python3_5 python3_6"}
     Installed versions:  2.79(19:39:30 24/01/2018)(bullet dds elbeem ffmpeg game-engine jack jpeg2k nls openexr openmp sdl sndfile tiff -collada -colorio -cuda -cycles -debug -doc -fftw -headless -jemalloc -libav -llvm -man -ndof -openal -opencl -openimageio -opensubdiv -openvdb -osl -player -test -valgrind PYTHON_SINGLE_TARGET="python3_5 -python3_6" PYTHON_TARGETS="python3_5 -python3_6")
     Homepage:            http://www.blender.org
     Description:         3D Creation/Animation/Publishing System


I can try again.
Had major software issues the last week, am still a bit battered from trying to fix  them but will try again and advise.

Thanks, Ian

**Comment by iandoug** [comment]
ah, that helps .. I see a -cycles there... no idea why. I'll force it on and re-compile.

**Comment by iandoug** [comment]
Okay seems to be working now ... guess I will have to find a Big Dummy's guide to Blender.

Thanks, Ian

**Comment by iandoug** [comment]
whoops spoke too soon.
I was able to open your samples like cochofur and wasd, but opening KLE json still produces wrong results (attached)

But don't see any error messages... 
![screenshot_20180129_212158](https://user-images.githubusercontent.com/12673886/35529895-0fbd99ce-053b-11e8-9d47-4dbee039ea49.jpg)

**Comment by iandoug** [comment]
error attached
![screenshot_20180129_212836](https://user-images.githubusercontent.com/12673886/35530035-8a10e122-053b-11e8-938f-c1cb110ec4ec.jpg)

**Comment by Kirpal** [comment]
Try adding colorio to the compile.

The error is when the add-on sets the Color management display device, the only available option is sRGB for you, but it should have None as an option. OpencolorIO is a color management library, and it looks like you didn't add it?

**Comment by iandoug** [comment]
Thanks, that worked, am able to load rectangular layouts like ANSI104, though will have to figure out how to steer the thing, show the keycaps and remove things that should not be there. Learning curve :-)

However get different errors when loading a more complex example...

Thanks, Ian
![screenshot_20180130_041918](https://user-images.githubusercontent.com/12673886/35544990-aa9df238-0575-11e8-8a86-ecad7e33d05d.png)
![screenshot_20180130_042041](https://user-images.githubusercontent.com/12673886/35545003-b3beccd4-0575-11e8-8538-5c6dfb4b11a9.png)
[pkb2.zip](https://github.com/Kirpal/Keyboard-Layout-Editor-for-Blender/files/1676162/pkb2.zip)

**Comment by Kirpal** [comment]
Looks like the same issue as #6... I'll check your layout to make sure, and then close this and continue work on that one

**Comment by iandoug** [comment]
Okay, thanks. For the record, in case someone else has similar issues, here's my current flags:

eix blender
[I] media-gfx/blender
     Available versions:  2.72b-r4 (~)2.79 {+boost +bullet collada colorio cuda cycles +dds debug doc +elbeem ffmpeg fftw +game-engine headless jack jemalloc jpeg2k libav llvm man ndof nls openal opencl +openexr openimageio openmp +opennl opensubdiv openvdb osl player redcode sdl sndfile test tiff valgrind CPU_FLAGS_X86="sse sse2" PYTHON_SINGLE_TARGET="python3_5 python3_6" PYTHON_TARGETS="python3_4 python3_5 python3_6"}

     Installed versions:  2.79(04:01:37 30/01/2018)(bullet colorio cycles dds elbeem ffmpeg game-engine jack jpeg2k nls openexr openimageio openmp sdl sndfile tiff -collada -cuda -debug -doc -fftw -headless -jemalloc -libav -llvm -man -ndof -openal -opencl -opensubdiv -openvdb -osl -player -test -valgrind PYTHON_SINGLE_TARGET="python3_5 -python3_6" PYTHON_TARGETS="python3_5 -python3_6")
     Homepage:            http://www.blender.org
     Description:         3D Creation/Animation/Publishing System
