### ISSUE TITLE
Error on importing json (v3.0)

### ISSUE THREAD

**Issue by gracjanzlotucha** [Kirpal/Keyboard-Layout-Editor-for-Blender#50]
Hey,

I've tried to import json file using new version of the file but I'm getting this error
![Annotation 2019-11-04 160908](https://user-images.githubusercontent.com/20012468/68131620-a5110000-ff1d-11e9-9870-34f579eaf019.png)

Any idea how to fix that?

**Comment by Kirpal** [comment]
I made a mistake in my release script and missed some files. The release is updated, would you mind reinstalling v3.0 and trying again?

**Comment by gracjanzlotucha** [comment]
Working now :)
