### ISSUE TITLE
Serious performance issues when importing KLE json file

### ISSUE THREAD

**Issue by DanielGGordon** [Kirpal/Keyboard-Layout-Editor-for-Blender#53]
Windows 10 Pro, Blender v2.80, v3.0 KLE for Blender

Importing a simple json file for something such a planck or ergodox takes 2+ minutes to import. I monitored resources during this time, and I also noticed a utilization of up to 17GB of memory during the json import. This seems very very high, and certainly 2+ minutes for a single import is a problem. 

I have not tested with 2.79, but will attempt to do that with the current version of this plugin.

**Comment by Raravin-Keebs** [comment]
My entire blender is actually just going not responsive not sure if it is normal or not importing.

**Comment by DanielGGordon** [comment]
@Raravin-Keebs yeah it actually for me looks like it is going to crash, but after 1.5 minutes it finally loads. I switched back to blender 2.79 and I don't have this issue at all.

**Comment by Raravin-Keebs** [comment]
Yeah I reverted to 2.79 and getting an issue with the .py

**Comment by DanielGGordon** [comment]
Hmm I don't have any issues with 2.79, although I have compared render results, and 2.80 seemed to produce more color accurate results. But that 1-2 minutes load time per .json is killer so I'm not using it.

**Comment by Kirpal** [comment]
Could you try again with the current master branch and see if you still have issues?

**Comment by StarrKiss** [comment]
I am getting this error on master branch, blender 2.82. It lasts up until 1.23 on the progress meter before blender crashes, using up ALL of my 16 gigs of ram. (i ran this in a terminal without enabling my desktop environment to test... It uses up ALL the ram if it can) It seems to work on smaller files, but on any large one (60-80 keys or more) it crashes. No idea why. I have a rather beefy computer, so I have no idea.

**Comment by snagy** [comment]
Weird.  I imported and rendered this "beauty" after my change without a problem: https://imgur.com/BpkC8aS

This was on a 32GB machine, but I don't think it would have crashed a 16 GB machine either.  I'll check it again soon and see if there's more room for improvement.

**Comment by StarrKiss** [comment]
This is the file I tried: 
[The KLE Link](http://www.keyboard-layout-editor.com/##@_name=CK75%20-%20ANSI%20Standard%3B&@_c=%2309b084&a:7%3B&=0&_x:0.5&c=%23cccccc%3B&=1&=2&=3&=4&_x:0.25&c=%2309b084%3B&=5&=6&=7&=8&_x:0.25&c=%23cccccc%3B&=9&=10&=11&=12%3B&@_y:0.25&c=%2309b084%3B&=13&_c=%23cccccc%3B&=14&=15&=16&=17&=18&=19&=20&=21&=22&=23&=24&=25&_c=%23cede02&w:2%3B&=26%3B&@_c=%2309b084&w:1.5%3B&=28&_c=%23cccccc%3B&=29&=30&=31&=32&=33&=34&=35&=36&=37&=38&=39&=40&_c=%2309b084&w:1.5%3B&=41&_x:0.5%3B&=42%3B&@_c=%23666ec4&w:1.75%3B&=43&_c=%23cccccc%3B&=44&=45&=46&=47&=48&=49&=50&=51&=52&=53&=54&_c=%2309b084&w:2.25%3B&=55&_x:0.5%3B&=56%3B&@_w:2.25%3B&=57&_c=%23cccccc%3B&=58&=59&=60&=61&=62&=63&=64&=65&=66&=67&_c=%2309b084&w:1.75%3B&=68&_x:1.5%3B&=70%3B&@_y:-0.75&x:14.25%3B&=69%3B&@_y:-0.25&w:1.25%3B&=71&_w:1.25%3B&=72&_w:1.25%3B&=73&_c=%23cccccc&w:6.25%3B&=74&_c=%23b00981%3B&=75&=76&=77%3B&@_y:-0.75&x:13.25&c=%2309b084%3B&=78&=79&=80)
It crashes at 0123 on the counter in Blender. I have tried this multiple times.

**Comment by snagy** [comment]
Thanks for the repro data!

Un/fortunately, i didn't see the issue. I successfully imported and topped out at about 2.5 gigs of memory usage after compiling shaders.

![tst_board](https://user-images.githubusercontent.com/696471/76274750-b9a03480-623e-11ea-8595-f649a5f3aa94.png)

Are you sure you have the latest version of the plugin installed?  I would recommend downloading the zip again, uninstalling the old one and then reinstalling from that new zip.

**Comment by StarrKiss** [comment]
Hello, I was able to get it working by zipping the github repo and installing that, unfortunately, the geometry is absolutely horrendous. All the shading has a seam down the middle of each cap, and it's unusable. I guess I have to go the long way.

**Comment by snagy** [comment]
Good to know the perf fix worked.

It looks like the shading seam happens on DSA/DCS (maybe cherry?  i didn't test it) profiles but doesn't happen for me on my SA layout.  If you can, please open another issue for the shading seam.

**Comment by DanielGGordon** [comment]
I have also noticed that line down the middle thing with DSA. Wasn't a show stopper for me. You can really only see it when you make a large resolution and zoom in. I used it for some product images for DSA Pink/Purple and I think it was fine.

**Comment by DanielGGordon** [comment]
This is really the same issue a #51 - still happens to me

**Comment by Hypn0tyk** [comment]
I am seeing that it uses a huge amount of memory and seems to hang forever on import.
![image](https://user-images.githubusercontent.com/53986111/79297089-b7b33c00-7ea2-11ea-8fac-e0065551a36d.png)

I tried a couple of times but I waited 5+ minutes and it never finished importing.  Fresh Blender install, latest release of plugin.

**Comment by Lorphex** [comment]
Same issue here. Running Blender 2.82a and importing freezes Blender for 2-ish minutes before crashing.

**Comment by sbinlondon** [comment]
Also unable to use v3.0 of this.

Macbook Pro 16-inch 2019 on Catalina OS 10.15.5
Blender 2.83.2 freshly installed

When I try to import the JSON my Blender immediately beachballs and starts consuming massive amounts of CPU and memory. Waited 5 minutes and it didn't import so I had to force quit.

<img width="760" alt="Screenshot 2020-07-10 at 17 09 40" src="https://user-images.githubusercontent.com/37520401/87175568-bd1cf880-c2d0-11ea-8aa7-68d697a22b2e.png">
<img width="506" alt="Screenshot 2020-07-10 at 17 09 49" src="https://user-images.githubusercontent.com/37520401/87175576-bee6bc00-c2d0-11ea-8220-9d76333be81e.png">

**Comment by ricardo-alan** [comment]
I couldn't use with the latest version of Blender, but 2.79 works perfect!

**Comment by snagy** [comment]
@Kirpal any chance we could get a new release built with the recent commits?  I think people are still installing 3.0 and seeing this.

**Comment by Kirpal** [comment]
@DanielGGordon Pretty much. I don't have the time to actively work on it and I'm not really in the mechkeys world anymore. Happy to accept PRs or add a maintainer if someone can help out

**Comment by Kirpal** [comment]
Working on a fix that should be out this week.
