### ISSUE TITLE
Keyboard Layout Incorrect

### ISSUE THREAD

**Issue by it4rz4n** [Kirpal/Keyboard-Layout-Editor-for-Blender#55]
Hi, whenever I load in any keyboard, whether is was the sample layouts or my own layout, I am given the image in the attached picture. I am not sure if there is something I am doing wrong or not.

![Capture](https://user-images.githubusercontent.com/62853960/79169574-08933980-7daa-11ea-852a-b984c0d332ac.PNG)

**Comment by Kirpal** [comment]
This is the output when it doesn't work for some reason. Are there any errors shown? Try looking in the python output if no message pops up.

**Comment by it4rz4n** [comment]
Thanks a lot! I just uninstalled and reinstalled Blender and it worked.
