### ISSUE TITLE
Location Issue

### ISSUE THREAD

**Issue by Allikchi** [Kirpal/Keyboard-Layout-Editor-for-Blender#67]
I downloaded this last night and followed the instructions with only slight variations since Blender has changed some menu options since the instructional was made. I went to import the .json file of my KLE design and blender fired a location error, "struct rna type of vector font has been removed." I didn't change anything actual files or locations, so I'm not sure what's happening.
I also don't really work with Blender often, so if it's something obvious then I apologize.

**Comment by Kirpal** [comment]
Did you download version 3.1? If you look in your blender addon preferences it should say the version

**Comment by Kirpal** [comment]
Please reopen if it is still happening.
