### ISSUE TITLE
Error on json import

### ISSUE THREAD

**Issue by TheWithz** [Kirpal/Keyboard-Layout-Editor-for-Blender#68]
After File>import KLE Raw Data I receive this error:

> Traceback (most recent call last):
>  File "/home/thewithz/.config/blender/2.90/scripts/addons/Keyboard-Layout-Editor-for-Blender/__init__.py", line 30, in execute
>    return import_keyboard.load_json(self, self.filepath)
>  File "/home/thewithz/.config/blender/2.90/scripts/addons/Keyboard-Layout-Editor-for-Blender/import_keyboard.py", line 373, in > load_json
>    read(filepath)
>  File "/home/thewithz/.config/blender/2.90/scripts/addons/Keyboard-Layout-Editor-for-Blender/import_keyboard.py", line 89, in read
>    scn.display_settings.display_device = "None"
> TypeError: bpy_struct: item.attr = val: enum "None" not found in ('sRGB')
> location: <unknown location>:-1

I am using the .blend file recommended from the gist in the README.
Blender version 2.90.1 on Gentoo Linux 5.9.1

**Comment by TheWithz** [comment]
Here's the json if that's relevant:
> ["~\n`","!\n1","@\n2","#\n3","$\n4","%\n5","^\n6","&\n7","*\n8","(\n9",")\n0","_\n-","+\n=",{w:2},"Backspace"],
> [{w:1.5},"Tab","Q","W","E","R","T","Y","U","I","O","P","{\n[","}\n]",{w:1.5},"|\n\\"],
> [{w:1.75},"Caps Lock","A","S","D","F","G","H","J","K","L",":\n;","\"\n'",{w:2.25},"Enter"],
> [{w:2.25},"Shift","Z","X","C","V","B","N","M","<\n,",">\n.","?\n/",{w:2.75},"Shift"],
> [{w:1.25},"Ctrl",{w:1.25},"Win",{w:1.25},"Alt",{a:7,w:6.25},"",{a:4,w:1.25},"Alt",{w:1.25},"Win",{w:1.25},"Fn",{w:1.25},"Ctrl"]

**Comment by Kirpal** [comment]
What build flags did you use to install blender?

See here: https://github.com/Kirpal/Keyboard-Layout-Editor-for-Blender/issues/5#issuecomment-361422978

**Comment by TheWithz** [comment]
I originally ran `emerge --ask media-gfx/blender` but I have the `CUDA` use flag enabled for the system. 

running with `USE="-opengl color-management" emerge --ask media-gfx/blender`
fixed the previous issue, per the gentoo wiki https://packages.gentoo.org/useflags/color-management
and then exposed another one. it appears I'm also missing cycles. 

> Traceback (most recent call last):
>  File "/home/thewithz/.config/blender/2.90/scripts/addons/Keyboard-Layout-Editor-for-Blender/__init__.py", line 30, in execute
>    return import_keyboard.load_json(self, self.filepath)
>   File "/home/thewithz/.config/blender/2.90/scripts/addons/Keyboard-Layout-Editor-for-Blender/import_keyboard.py", line 373, in load_json
>    read(filepath)
>  File "/home/thewithz/.config/blender/2.90/scripts/addons/Keyboard-Layout-Editor-for-Blender/import_keyboard.py", line 90, in >read
>    scn.render.engine = 'CYCLES'
> TypeError: bpy_struct: item.attr = val: enum "CYCLES" not found in ('BLENDER_EEVEE', 'BLENDER_WORKBENCH')
> location: <unknown location>:-1

To solve this I tried the below, but the new CYCLES error still persists. 
`USE="-opengl color-management openimageio cycles" emerge --ask media-gfx/blender` which requires media-libs/openimageio and dev-libs/boost to be preinstalled.

**Comment by TheWithz** [comment]
Hmmm. I seemed to have missed the step where cycles is also an add-on. After doing that I've got it working.
