### ISSUE TITLE
Issue loading in text sizes

### ISSUE THREAD

**Issue by Frowsty** [Kirpal/Keyboard-Layout-Editor-for-Blender#71]
**Required Information**
- [Blender version] 2.90.1
- [Add-on version] v3.1
- [Link to the layout] http://www.keyboard-layout-editor.com/#/gists/ea63e70bc762c0eb54012d2481c10ef4

**Describe the bug**
Not sure if it's a bug or intentional but the text size is not being imported. Is this a known issue or is it intentional?

**Screenshots**
Blender version
![JokerTheme](https://user-images.githubusercontent.com/46590835/100027268-c70d4700-2dec-11eb-8ee2-dc1045a36c4a.png)

Straight from KLE
![keyboard-layout (3)](https://user-images.githubusercontent.com/46590835/100027336-dee4cb00-2dec-11eb-923a-69d94bf0c29e.png)

The text size is not the same, some keys in blender turn out correct like arrows and brackets but more often than not it fails to replicate the sizes from KLE

**Comment by Kirpal** [comment]
Should be fixed now, thanks for catching this!
